/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankyouRouteImport } from './routes/thankyou'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MlsListingsRouteImport } from './routes/mls-listings'
import { Route as MileageRouteImport } from './routes/mileage'
import { Route as MediaStorageRouteImport } from './routes/media-storage'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DotloopRouteImport } from './routes/dotloop'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalenderRouteImport } from './routes/calender'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksTransactionsRouteImport } from './routes/books.transactions'
import { Route as BooksTaxesRouteImport } from './routes/books.taxes'
import { Route as BooksReportsRouteImport } from './routes/books.reports'
import { Route as BooksOwnerLoanRouteImport } from './routes/books.owner-loan'
import { Route as BooksCategoriesRouteImport } from './routes/books.categories'
import { Route as BooksAccountsRouteImport } from './routes/books.accounts'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsApplyTaxCodesRouteImport } from './routes/api/public/payments/apply-tax-codes'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api/public/google/calendar-callback'
import { Route as ApiPublicGhlWebhookRouteImport } from './routes/api/public/ghl.webhook'

const ThankyouRoute = ThankyouRouteImport.update({
  id: '/thankyou',
  path: '/thankyou',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MlsListingsRoute = MlsListingsRouteImport.update({
  id: '/mls-listings',
  path: '/mls-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MileageRoute = MileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaStorageRoute = MediaStorageRouteImport.update({
  id: '/media-storage',
  path: '/media-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DotloopRoute = DotloopRouteImport.update({
  id: '/dotloop',
  path: '/dotloop',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalenderRoute = CalenderRouteImport.update({
  id: '/calender',
  path: '/calender',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksTransactionsRoute = BooksTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => BooksRoute,
} as any)
const BooksTaxesRoute = BooksTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => BooksRoute,
} as any)
const BooksReportsRoute = BooksReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BooksRoute,
} as any)
const BooksOwnerLoanRoute = BooksOwnerLoanRouteImport.update({
  id: '/owner-loan',
  path: '/owner-loan',
  getParentRoute: () => BooksRoute,
} as any)
const BooksCategoriesRoute = BooksCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BooksRoute,
} as any)
const BooksAccountsRoute = BooksAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => BooksRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsApplyTaxCodesRoute =
  ApiPublicPaymentsApplyTaxCodesRouteImport.update({
    id: '/api/public/payments/apply-tax-codes',
    path: '/api/public/payments/apply-tax-codes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google/calendar-callback',
    path: '/api/public/google/calendar-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGhlWebhookRoute = ApiPublicGhlWebhookRouteImport.update({
  id: '/api/public/ghl/webhook',
  path: '/api/public/ghl/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/books': typeof BooksRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/calender': typeof CalenderRoute
  '/clients': typeof ClientsRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/dotloop': typeof DotloopRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/listings': typeof ListingsRoute
  '/media-storage': typeof MediaStorageRoute
  '/mileage': typeof MileageRoute
  '/mls-listings': typeof MlsListingsRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/thankyou': typeof ThankyouRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/taxes': typeof BooksTaxesRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books/': typeof BooksIndexRoute
  '/api/public/ghl/webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/google/calendar-callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/payments/apply-tax-codes': typeof ApiPublicPaymentsApplyTaxCodesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/calendar': typeof CalendarRoute
  '/calender': typeof CalenderRoute
  '/clients': typeof ClientsRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/dotloop': typeof DotloopRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/listings': typeof ListingsRoute
  '/media-storage': typeof MediaStorageRoute
  '/mileage': typeof MileageRoute
  '/mls-listings': typeof MlsListingsRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/thankyou': typeof ThankyouRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/taxes': typeof BooksTaxesRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books': typeof BooksIndexRoute
  '/api/public/ghl/webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/google/calendar-callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/payments/apply-tax-codes': typeof ApiPublicPaymentsApplyTaxCodesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/books': typeof BooksRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/calender': typeof CalenderRoute
  '/clients': typeof ClientsRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/dotloop': typeof DotloopRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/listings': typeof ListingsRoute
  '/media-storage': typeof MediaStorageRoute
  '/mileage': typeof MileageRoute
  '/mls-listings': typeof MlsListingsRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/test': typeof TestRoute
  '/thankyou': typeof ThankyouRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/taxes': typeof BooksTaxesRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books/': typeof BooksIndexRoute
  '/api/public/ghl/webhook': typeof ApiPublicGhlWebhookRoute
  '/api/public/google/calendar-callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/payments/apply-tax-codes': typeof ApiPublicPaymentsApplyTaxCodesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/books'
    | '/calendar'
    | '/calender'
    | '/clients'
    | '/commissions'
    | '/dashboard'
    | '/deals'
    | '/documents'
    | '/dotloop'
    | '/expenses'
    | '/forgot-password'
    | '/help'
    | '/landing'
    | '/listings'
    | '/media-storage'
    | '/mileage'
    | '/mls-listings'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/receipts'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/support'
    | '/tasks'
    | '/terms'
    | '/terms-and-conditions'
    | '/test'
    | '/thankyou'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/taxes'
    | '/books/transactions'
    | '/books/'
    | '/api/public/ghl/webhook'
    | '/api/public/google/calendar-callback'
    | '/api/public/payments/apply-tax-codes'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/calendar'
    | '/calender'
    | '/clients'
    | '/commissions'
    | '/dashboard'
    | '/deals'
    | '/documents'
    | '/dotloop'
    | '/expenses'
    | '/forgot-password'
    | '/help'
    | '/landing'
    | '/listings'
    | '/media-storage'
    | '/mileage'
    | '/mls-listings'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/receipts'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/support'
    | '/tasks'
    | '/terms'
    | '/terms-and-conditions'
    | '/test'
    | '/thankyou'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/taxes'
    | '/books/transactions'
    | '/books'
    | '/api/public/ghl/webhook'
    | '/api/public/google/calendar-callback'
    | '/api/public/payments/apply-tax-codes'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/billing'
    | '/books'
    | '/calendar'
    | '/calender'
    | '/clients'
    | '/commissions'
    | '/dashboard'
    | '/deals'
    | '/documents'
    | '/dotloop'
    | '/expenses'
    | '/forgot-password'
    | '/help'
    | '/landing'
    | '/listings'
    | '/media-storage'
    | '/mileage'
    | '/mls-listings'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/receipts'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/support'
    | '/tasks'
    | '/terms'
    | '/terms-and-conditions'
    | '/test'
    | '/thankyou'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/taxes'
    | '/books/transactions'
    | '/books/'
    | '/api/public/ghl/webhook'
    | '/api/public/google/calendar-callback'
    | '/api/public/payments/apply-tax-codes'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  BooksRoute: typeof BooksRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CalenderRoute: typeof CalenderRoute
  ClientsRoute: typeof ClientsRoute
  CommissionsRoute: typeof CommissionsRoute
  DashboardRoute: typeof DashboardRoute
  DealsRoute: typeof DealsRoute
  DocumentsRoute: typeof DocumentsRoute
  DotloopRoute: typeof DotloopRoute
  ExpensesRoute: typeof ExpensesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LandingRoute: typeof LandingRoute
  ListingsRoute: typeof ListingsRoute
  MediaStorageRoute: typeof MediaStorageRoute
  MileageRoute: typeof MileageRoute
  MlsListingsRoute: typeof MlsListingsRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TestRoute: typeof TestRoute
  ThankyouRoute: typeof ThankyouRoute
  ApiPublicGhlWebhookRoute: typeof ApiPublicGhlWebhookRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
  ApiPublicPaymentsApplyTaxCodesRoute: typeof ApiPublicPaymentsApplyTaxCodesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thankyou': {
      id: '/thankyou'
      path: '/thankyou'
      fullPath: '/thankyou'
      preLoaderRoute: typeof ThankyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mls-listings': {
      id: '/mls-listings'
      path: '/mls-listings'
      fullPath: '/mls-listings'
      preLoaderRoute: typeof MlsListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mileage': {
      id: '/mileage'
      path: '/mileage'
      fullPath: '/mileage'
      preLoaderRoute: typeof MileageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-storage': {
      id: '/media-storage'
      path: '/media-storage'
      fullPath: '/media-storage'
      preLoaderRoute: typeof MediaStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dotloop': {
      id: '/dotloop'
      path: '/dotloop'
      fullPath: '/dotloop'
      preLoaderRoute: typeof DotloopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calender': {
      id: '/calender'
      path: '/calender'
      fullPath: '/calender'
      preLoaderRoute: typeof CalenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/transactions': {
      id: '/books/transactions'
      path: '/transactions'
      fullPath: '/books/transactions'
      preLoaderRoute: typeof BooksTransactionsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/taxes': {
      id: '/books/taxes'
      path: '/taxes'
      fullPath: '/books/taxes'
      preLoaderRoute: typeof BooksTaxesRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/reports': {
      id: '/books/reports'
      path: '/reports'
      fullPath: '/books/reports'
      preLoaderRoute: typeof BooksReportsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/owner-loan': {
      id: '/books/owner-loan'
      path: '/owner-loan'
      fullPath: '/books/owner-loan'
      preLoaderRoute: typeof BooksOwnerLoanRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/categories': {
      id: '/books/categories'
      path: '/categories'
      fullPath: '/books/categories'
      preLoaderRoute: typeof BooksCategoriesRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/accounts': {
      id: '/books/accounts'
      path: '/accounts'
      fullPath: '/books/accounts'
      preLoaderRoute: typeof BooksAccountsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/apply-tax-codes': {
      id: '/api/public/payments/apply-tax-codes'
      path: '/api/public/payments/apply-tax-codes'
      fullPath: '/api/public/payments/apply-tax-codes'
      preLoaderRoute: typeof ApiPublicPaymentsApplyTaxCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/calendar-callback': {
      id: '/api/public/google/calendar-callback'
      path: '/api/public/google/calendar-callback'
      fullPath: '/api/public/google/calendar-callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ghl/webhook': {
      id: '/api/public/ghl/webhook'
      path: '/api/public/ghl/webhook'
      fullPath: '/api/public/ghl/webhook'
      preLoaderRoute: typeof ApiPublicGhlWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BooksRouteChildren {
  BooksAccountsRoute: typeof BooksAccountsRoute
  BooksCategoriesRoute: typeof BooksCategoriesRoute
  BooksOwnerLoanRoute: typeof BooksOwnerLoanRoute
  BooksReportsRoute: typeof BooksReportsRoute
  BooksTaxesRoute: typeof BooksTaxesRoute
  BooksTransactionsRoute: typeof BooksTransactionsRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksAccountsRoute: BooksAccountsRoute,
  BooksCategoriesRoute: BooksCategoriesRoute,
  BooksOwnerLoanRoute: BooksOwnerLoanRoute,
  BooksReportsRoute: BooksReportsRoute,
  BooksTaxesRoute: BooksTaxesRoute,
  BooksTransactionsRoute: BooksTransactionsRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  BooksRoute: BooksRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CalenderRoute: CalenderRoute,
  ClientsRoute: ClientsRoute,
  CommissionsRoute: CommissionsRoute,
  DashboardRoute: DashboardRoute,
  DealsRoute: DealsRoute,
  DocumentsRoute: DocumentsRoute,
  DotloopRoute: DotloopRoute,
  ExpensesRoute: ExpensesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LandingRoute: LandingRoute,
  ListingsRoute: ListingsRoute,
  MediaStorageRoute: MediaStorageRoute,
  MileageRoute: MileageRoute,
  MlsListingsRoute: MlsListingsRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ReceiptsRoute: ReceiptsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TestRoute: TestRoute,
  ThankyouRoute: ThankyouRoute,
  ApiPublicGhlWebhookRoute: ApiPublicGhlWebhookRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
  ApiPublicPaymentsApplyTaxCodesRoute: ApiPublicPaymentsApplyTaxCodesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
