/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MileageRouteImport } from './routes/mileage'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksTransactionsRouteImport } from './routes/books.transactions'
import { Route as BooksTaxesRouteImport } from './routes/books.taxes'
import { Route as BooksReportsRouteImport } from './routes/books.reports'
import { Route as BooksOwnerLoanRouteImport } from './routes/books.owner-loan'
import { Route as BooksCategoriesRouteImport } from './routes/books.categories'
import { Route as BooksAccountsRouteImport } from './routes/books.accounts'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsApplyTaxCodesRouteImport } from './routes/api/public/payments/apply-tax-codes'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MileageRoute = MileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksTransactionsRoute = BooksTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => BooksRoute,
} as any)
const BooksTaxesRoute = BooksTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => BooksRoute,
} as any)
const BooksReportsRoute = BooksReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BooksRoute,
} as any)
const BooksOwnerLoanRoute = BooksOwnerLoanRouteImport.update({
  id: '/owner-loan',
  path: '/owner-loan',
  getParentRoute: () => BooksRoute,
} as any)
const BooksCategoriesRoute = BooksCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BooksRoute,
} as any)
const BooksAccountsRoute = BooksAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => BooksRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsApplyTaxCodesRoute =
  ApiPublicPaymentsApplyTaxCodesRouteImport.update({
    id: '/api/public/payments/apply-tax-codes',
    path: '/api/public/payments/apply-tax-codes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/books': typeof BooksRouteWithChildren
  '/clients': typeof ClientsRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/landing': typeof LandingRoute
  '/listings': typeof ListingsRoute
  '/mileage': typeof MileageRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/taxes': typeof BooksTaxesRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books/': typeof BooksIndexRoute
  '/api/public/payments/apply-tax-codes': typeof ApiPublicPaymentsApplyTaxCodesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/clients': typeof ClientsRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/landing': typeof LandingRoute
  '/listings': typeof ListingsRoute
  '/mileage': typeof MileageRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/taxes': typeof BooksTaxesRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books': typeof BooksIndexRoute
  '/api/public/payments/apply-tax-codes': typeof ApiPublicPaymentsApplyTaxCodesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/books': typeof BooksRouteWithChildren
  '/clients': typeof ClientsRoute
  '/deals': typeof DealsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/landing': typeof LandingRoute
  '/listings': typeof ListingsRoute
  '/mileage': typeof MileageRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/taxes': typeof BooksTaxesRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books/': typeof BooksIndexRoute
  '/api/public/payments/apply-tax-codes': typeof ApiPublicPaymentsApplyTaxCodesRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/books'
    | '/clients'
    | '/deals'
    | '/documents'
    | '/expenses'
    | '/forgot-password'
    | '/help'
    | '/invoices'
    | '/landing'
    | '/listings'
    | '/mileage'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/receipts'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/taxes'
    | '/books/transactions'
    | '/books/'
    | '/api/public/payments/apply-tax-codes'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/clients'
    | '/deals'
    | '/documents'
    | '/expenses'
    | '/forgot-password'
    | '/help'
    | '/invoices'
    | '/landing'
    | '/listings'
    | '/mileage'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/receipts'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/taxes'
    | '/books/transactions'
    | '/books'
    | '/api/public/payments/apply-tax-codes'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/billing'
    | '/books'
    | '/clients'
    | '/deals'
    | '/documents'
    | '/expenses'
    | '/forgot-password'
    | '/help'
    | '/invoices'
    | '/landing'
    | '/listings'
    | '/mileage'
    | '/pipeline'
    | '/pricing'
    | '/privacy'
    | '/receipts'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/taxes'
    | '/books/transactions'
    | '/books/'
    | '/api/public/payments/apply-tax-codes'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  BooksRoute: typeof BooksRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  DealsRoute: typeof DealsRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpensesRoute: typeof ExpensesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  InvoicesRoute: typeof InvoicesRoute
  LandingRoute: typeof LandingRoute
  ListingsRoute: typeof ListingsRoute
  MileageRoute: typeof MileageRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiPublicPaymentsApplyTaxCodesRoute: typeof ApiPublicPaymentsApplyTaxCodesRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mileage': {
      id: '/mileage'
      path: '/mileage'
      fullPath: '/mileage'
      preLoaderRoute: typeof MileageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/transactions': {
      id: '/books/transactions'
      path: '/transactions'
      fullPath: '/books/transactions'
      preLoaderRoute: typeof BooksTransactionsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/taxes': {
      id: '/books/taxes'
      path: '/taxes'
      fullPath: '/books/taxes'
      preLoaderRoute: typeof BooksTaxesRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/reports': {
      id: '/books/reports'
      path: '/reports'
      fullPath: '/books/reports'
      preLoaderRoute: typeof BooksReportsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/owner-loan': {
      id: '/books/owner-loan'
      path: '/owner-loan'
      fullPath: '/books/owner-loan'
      preLoaderRoute: typeof BooksOwnerLoanRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/categories': {
      id: '/books/categories'
      path: '/categories'
      fullPath: '/books/categories'
      preLoaderRoute: typeof BooksCategoriesRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/accounts': {
      id: '/books/accounts'
      path: '/accounts'
      fullPath: '/books/accounts'
      preLoaderRoute: typeof BooksAccountsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/apply-tax-codes': {
      id: '/api/public/payments/apply-tax-codes'
      path: '/api/public/payments/apply-tax-codes'
      fullPath: '/api/public/payments/apply-tax-codes'
      preLoaderRoute: typeof ApiPublicPaymentsApplyTaxCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BooksRouteChildren {
  BooksAccountsRoute: typeof BooksAccountsRoute
  BooksCategoriesRoute: typeof BooksCategoriesRoute
  BooksOwnerLoanRoute: typeof BooksOwnerLoanRoute
  BooksReportsRoute: typeof BooksReportsRoute
  BooksTaxesRoute: typeof BooksTaxesRoute
  BooksTransactionsRoute: typeof BooksTransactionsRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksAccountsRoute: BooksAccountsRoute,
  BooksCategoriesRoute: BooksCategoriesRoute,
  BooksOwnerLoanRoute: BooksOwnerLoanRoute,
  BooksReportsRoute: BooksReportsRoute,
  BooksTaxesRoute: BooksTaxesRoute,
  BooksTransactionsRoute: BooksTransactionsRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  BooksRoute: BooksRouteWithChildren,
  ClientsRoute: ClientsRoute,
  DealsRoute: DealsRoute,
  DocumentsRoute: DocumentsRoute,
  ExpensesRoute: ExpensesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  InvoicesRoute: InvoicesRoute,
  LandingRoute: LandingRoute,
  ListingsRoute: ListingsRoute,
  MileageRoute: MileageRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReceiptsRoute: ReceiptsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiPublicPaymentsApplyTaxCodesRoute: ApiPublicPaymentsApplyTaxCodesRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
