/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as MileageRouteImport } from './routes/mileage'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksTransactionsRouteImport } from './routes/books.transactions'
import { Route as BooksReportsRouteImport } from './routes/books.reports'
import { Route as BooksOwnerLoanRouteImport } from './routes/books.owner-loan'
import { Route as BooksCategoriesRouteImport } from './routes/books.categories'
import { Route as BooksAccountsRouteImport } from './routes/books.accounts'

const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MileageRoute = MileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksRoute,
} as any)
const BooksTransactionsRoute = BooksTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => BooksRoute,
} as any)
const BooksReportsRoute = BooksReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => BooksRoute,
} as any)
const BooksOwnerLoanRoute = BooksOwnerLoanRouteImport.update({
  id: '/owner-loan',
  path: '/owner-loan',
  getParentRoute: () => BooksRoute,
} as any)
const BooksCategoriesRoute = BooksCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BooksRoute,
} as any)
const BooksAccountsRoute = BooksAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => BooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/listings': typeof ListingsRoute
  '/mileage': typeof MileageRoute
  '/pipeline': typeof PipelineRoute
  '/receipts': typeof ReceiptsRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/listings': typeof ListingsRoute
  '/mileage': typeof MileageRoute
  '/pipeline': typeof PipelineRoute
  '/receipts': typeof ReceiptsRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRouteWithChildren
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/help': typeof HelpRoute
  '/invoices': typeof InvoicesRoute
  '/listings': typeof ListingsRoute
  '/mileage': typeof MileageRoute
  '/pipeline': typeof PipelineRoute
  '/receipts': typeof ReceiptsRoute
  '/books/accounts': typeof BooksAccountsRoute
  '/books/categories': typeof BooksCategoriesRoute
  '/books/owner-loan': typeof BooksOwnerLoanRoute
  '/books/reports': typeof BooksReportsRoute
  '/books/transactions': typeof BooksTransactionsRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/clients'
    | '/documents'
    | '/expenses'
    | '/help'
    | '/invoices'
    | '/listings'
    | '/mileage'
    | '/pipeline'
    | '/receipts'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/transactions'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/documents'
    | '/expenses'
    | '/help'
    | '/invoices'
    | '/listings'
    | '/mileage'
    | '/pipeline'
    | '/receipts'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/transactions'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/clients'
    | '/documents'
    | '/expenses'
    | '/help'
    | '/invoices'
    | '/listings'
    | '/mileage'
    | '/pipeline'
    | '/receipts'
    | '/books/accounts'
    | '/books/categories'
    | '/books/owner-loan'
    | '/books/reports'
    | '/books/transactions'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpensesRoute: typeof ExpensesRoute
  HelpRoute: typeof HelpRoute
  InvoicesRoute: typeof InvoicesRoute
  ListingsRoute: typeof ListingsRoute
  MileageRoute: typeof MileageRoute
  PipelineRoute: typeof PipelineRoute
  ReceiptsRoute: typeof ReceiptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mileage': {
      id: '/mileage'
      path: '/mileage'
      fullPath: '/mileage'
      preLoaderRoute: typeof MileageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/transactions': {
      id: '/books/transactions'
      path: '/transactions'
      fullPath: '/books/transactions'
      preLoaderRoute: typeof BooksTransactionsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/reports': {
      id: '/books/reports'
      path: '/reports'
      fullPath: '/books/reports'
      preLoaderRoute: typeof BooksReportsRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/owner-loan': {
      id: '/books/owner-loan'
      path: '/owner-loan'
      fullPath: '/books/owner-loan'
      preLoaderRoute: typeof BooksOwnerLoanRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/categories': {
      id: '/books/categories'
      path: '/categories'
      fullPath: '/books/categories'
      preLoaderRoute: typeof BooksCategoriesRouteImport
      parentRoute: typeof BooksRoute
    }
    '/books/accounts': {
      id: '/books/accounts'
      path: '/accounts'
      fullPath: '/books/accounts'
      preLoaderRoute: typeof BooksAccountsRouteImport
      parentRoute: typeof BooksRoute
    }
  }
}

interface BooksRouteChildren {
  BooksAccountsRoute: typeof BooksAccountsRoute
  BooksCategoriesRoute: typeof BooksCategoriesRoute
  BooksOwnerLoanRoute: typeof BooksOwnerLoanRoute
  BooksReportsRoute: typeof BooksReportsRoute
  BooksTransactionsRoute: typeof BooksTransactionsRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksAccountsRoute: BooksAccountsRoute,
  BooksCategoriesRoute: BooksCategoriesRoute,
  BooksOwnerLoanRoute: BooksOwnerLoanRoute,
  BooksReportsRoute: BooksReportsRoute,
  BooksTransactionsRoute: BooksTransactionsRoute,
  BooksIndexRoute: BooksIndexRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRouteWithChildren,
  ClientsRoute: ClientsRoute,
  DocumentsRoute: DocumentsRoute,
  ExpensesRoute: ExpensesRoute,
  HelpRoute: HelpRoute,
  InvoicesRoute: InvoicesRoute,
  ListingsRoute: ListingsRoute,
  MileageRoute: MileageRoute,
  PipelineRoute: PipelineRoute,
  ReceiptsRoute: ReceiptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
